data_path:
  dado3: 'data/raw/seeds/' 
  dado4: 'data/raw/dado4/'
  dado1: 'data/raw/dado1/'

database_params:
  dado3:
    fs: 2048
    nrows_forearm: 9
    ncolumns_forearm: 14
    elec_diameter: 1.95
    elec_distance: 4
    database_url: 'https://osf.io/wa3qk/'
    subj01:
      age: 30
      gender: 'F'
      dom_hand: 'L'
    subj02:
      age: 30
      gender: 'F'
      dom_hand: 'R'
    subj03:
      age: 38
      gender: 'M'
      dom_hand: 'R'
    subj04:
      age: 29
      gender: 'M'
      dom_hand: 'R'
    subj05:
      age: 24
      gender: 'F'
      dom_hand: 'R'
    subj06:
      age: 32
      gender: 'M'
      dom_hand: 'R'
    subj07:
      age: 34
      gender: 'F'
      dom_hand: 'R'
    subj08:
      age: 28
      gender: 'M'
      dom_hand: 'R'
    subj09:
      age: 21
      gender: 'M'
      dom_hand: 'R'
    subj10:
      age: 55
      gender: 'F'
      dom_hand: 'R'
    subj11:
      age: 26
      gender: 'F'
      dom_hand: 'R'
    subj12:
      age: 27
      gender: 'F'
      dom_hand: 'R'
    subj13:
      age: 29
      gender: 'M'
      dom_hand: 'R'
    subj14:
      age: 47
      gender: 'M'
      dom_hand: 'R'
    subj15:
      age: 24
      gender: 'F'
      dom_hand: 'R'
    subj16:
      age: 46
      gender: 'M'
      dom_hand: 'R'
    subj17:
      age: 47
      gender: 'F'
      dom_hand: 'R'
    subj18:
      age: 49
      gender: 'F'
      dom_hand: 'R'
    subj19:
      age: 29
      gender: 'F'
      dom_hand: 'R'
    subj20:
      age: 32
      gender: 'F'
      dom_hand: 'L'
    subj21:
      age: 30
      gender: 'F'
      dom_hand: 'R'
    subj22:
      age: 43
      gender: 'M'
      dom_hand: 'R'
    subj23:
      age: 40
      gender: 'F'
      dom_hand: 'R'
    subj24:
      age: 24
      gender: 'M'
      dom_hand: 'R'
    subj25:
      age: 18
      gender: 'M'
      dom_hand: 'R'
  dado4:
    fs: 2048
    nrows_forearm: 6
    nrows_biceps: 8
    nrows_triceps: 8
    ncolumns_biceps: 15
    ncolumns_triceps: 15
    elec_diameter: 5
    elec_distance: 10
    database_url: 'https://www.nature.com/articles/s41597-020-00717-6#Sec7'
    
  dado2:
    frequence_sample: 2048
    nrows_emgextensor: 8
    nrows_emgflexor: 8
    ncolumns_biceps: 8
    ncolumns_triceps: 8
    elec_diameter: 'na'
    elec_distance: 10
    database_url: 'https://www.nature.com/articles/s41597-021-00843-9'

    s1:
      age: 24
      gender: 'female'
      height_cm: 165
      palm_width_cm: 9
      palm_circumference_cm: 20
      forearm_circumference_cm: 23
      weight_kg: 56
      laterality: 'right'

    s2:
      age: 23
      gender: 'male'
      height_cm: 174
      palm_width_cm: 9
      palm_circumference_cm: 21
      forearm_circumference_cm: 26.5
      weight_kg: 77
      laterality: 'right'

    s3:
      age: 25
      gender: 'male'
      height_cm: 170
      palm_width_cm: 8
      palm_circumference_cm: 19
      forearm_circumference_cm: 22.4
      weight_kg: 65
      laterality: 'right'

    s4:
      age: 24
      gender: 'male'
      height_cm: 168
      palm_width_cm: 8
      palm_circumference_cm: 20
      forearm_circumference_cm: 22
      weight_kg: 58
      laterality: 'right'

    s5:
      age: 23
      gender: 'female'
      height_cm: 160
      palm_width_cm: 7
      palm_circumference_cm: 19
      forearm_circumference_cm: 20
      weight_kg: 48
      laterality: 'right'

    s6:
      age: 26
      gender: 'male'
      height_cm: 175
      palm_width_cm: 9
      palm_circumference_cm: 21
      forearm_circumference_cm: 27
      weight_kg: 75
      laterality: 'right'

    s7:
      age: 23
      gender: 'male'
      height_cm: 180
      palm_width_cm: 10
      palm_circumference_cm: 23
      forearm_circumference_cm: 27
      weight_kg: 75
      laterality: 'right'

    s8:
      age: 23
      gender: 'male'
      height_cm: 173
      palm_width_cm: 8.5
      palm_circumference_cm: 20
      forearm_circumference_cm: 25
      weight_kg: 65
      laterality: 'right'

    s9:
      age: 23
      gender: 'female'
      height_cm: 163
      palm_width_cm: 7.4
      palm_circumference_cm: 16.8
      forearm_circumference_cm: 20
      weight_kg: 51
      laterality: 'right'

    s10:
      age: 25
      gender: 'female'
      height_cm: 154
      palm_width_cm: 7
      palm_circumference_cm: 16.7
      forearm_circumference_cm: 18.4
      weight_kg: 38
      laterality: 'right'

    s11:
      age: 25
      gender: 'male'
      height_cm: 177
      palm_width_cm: 8.4
      palm_circumference_cm: 21
      forearm_circumference_cm: 25.2
      weight_kg: 70
      laterality: 'right'

    s12:
      age: 24
      gender: 'male'
      height_cm: 176
      palm_width_cm: 8.4
      palm_circumference_cm: 19
      forearm_circumference_cm: 24.4
      weight_kg: 65
      laterality: 'right'

    s13:
      age: 26
      gender: 'male'
      height_cm: 175
      palm_width_cm: 9
      palm_circumference_cm: 20.6
      forearm_circumference_cm: 26
      weight_kg: 67
      laterality: 'right'

    s14:
      age: 24
      gender: 'female'
      height_cm: 170
      palm_width_cm: 7.6
      palm_circumference_cm: 18.8
      forearm_circumference_cm: 22
      weight_kg: 56
      laterality: 'right'

    s15:
      age: 25
      gender: 'female'
      height_cm: 154
      palm_width_cm: 7
      palm_circumference_cm: 17.8
      forearm_circumference_cm: 20
      weight_kg: 45
      laterality: 'right'

    s16:
      age: 24
      gender: 'female'
      height_cm: 170
      palm_width_cm: 8
      palm_circumference_cm: 18.6
      forearm_circumference_cm: 22.4
      weight_kg: 60
      laterality: 'right'

    s17:
      age: 25
      gender: 'male'
      height_cm: 178
      palm_width_cm: 8.4
      palm_circumference_cm: 20
      forearm_circumference_cm: 24.8
      weight_kg: 75
      laterality: 'right'

    s18:
      age: 23
      gender: 'male'
      height_cm: 173
      palm_width_cm: 8.8
      palm_circumference_cm: 21
      forearm_circumference_cm: 28
      weight_kg: 89
      laterality: 'right'

    s19:
      age: 25
      gender: 'female'
      height_cm: 175
      palm_width_cm: 8
      palm_circumference_cm: 19
      forearm_circumference_cm: 20
      weight_kg: 60
      laterality: 'right'

    s20:
      age: 22
      gender: 'female'
      height_cm: 158
      palm_width_cm: 7
      palm_circumference_cm: 16.6
      forearm_circumference_cm: 21
      weight_kg: 43
      laterality: 'right'

